src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use function Symfony\Component\String\s;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'events')]
    private Collection $members;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $data = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $start = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $finish = null;

    public function __construct()
    {
        $this->members = new ArrayCollection();
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, User>
     */
    public function getMembers(): Collection
    {
        return $this->members;
    }

    public function addMember(User $member): self
    {
        if (!$this->members->contains($member)) {
            $this->members->add($member);
        }

        return $this;
    }

    public function removeMember(User $member): self
    {
        $this->members->removeElement($member);

        return $this;
    }

    public function getData(): ?string
    {
        return $this->data;
    }

    public function setData(?string $data): self
    {
        $this->data = $data;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(?\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getFinish(): ?\DateTimeInterface
    {
        return $this->finish;
    }

    public function setFinish(?\DateTimeInterface $finish): self
    {
        $this->finish = $finish;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
    {% block stylesheets %}
        {{ vite_entry_link_tags('app') }}
    {% endblock %}

    {% block javascripts %}
        {{ vite_entry_script_tags('app') }}
    {% endblock %}
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>

templates/home.twig
{% extends 'base.html.twig' %}
{% block title %}Home page - kedr test{% endblock %}

{% block body %}
    <div class="container min-h-screen flex flex-col items-center justify-center">
        <h1 class="text-4xl font-semibold mb-4">Test app - Events</h1>

        <div>
            {% if is_granted('ROLE_ADMIN') %}
                <a href="{{ url('admin') }}" class="btn btn-sm btn-primary m-2">EasyAdmin</a>
            {% endif %}

            {% if is_granted('ROLE_USER') %}
                <a href="{{ url('app_logout') }}" class="btn btn-sm">Logout</a>
            {% else %}
                <a href="{{ url('app_login') }}" class="btn btn-sm">Login</a>
            {% endif %}
        </div>

        {% if is_granted('ROLE_USER') %}
            <div class="overflow-x-auto w-full mt-4">
                <h2 class="text-2xl text-center font-semibold">User events</h2>
                <table class="w-full table">
                    <thead>
                    <tr>
                        <th>id</th>
                        <th>created At</th>
                        <th>start</th>
                        <th>finish</th>
                        <th>data</th>
                        <th>user ids</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for event in app.user.events %}
                        <tr>
                            <th>{{ event.id }}</th>
                            <th>{{ event.createdAt.format('Y-m-d h:i') }}</th>
                            <th>{{ event.start.format('Y-m-d h:i') }}</th>
                            <th>{% if event.finish %}
                                    {{ event.finish.format('Y-m-d h:i') }}
                                {% endif %}</th>
                            <th class="whitespace-nowrap">{{ event.data|raw }}</th>
                            <th>
                                {% for member in event.members %}
                                    <span class="mr-2 badge">{{ member.id }}</span>
                                {% endfor %}
                            </th>
                        </tr>
                    {% endfor %}
                    {% if app.user.events|length == 0 %}
                        <tr><th>Events not found</th></tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        {% endif %}

        {% if is_granted('ROLE_ADMIN') %}
            <div class="overflow-x-auto w-full mt-10">
                <h2 class="text-2xl text-center font-semibold">All events by date</h2>

                {% if groupedEvents|length == 0 %}
                    <div class="badge">Events not found</div>
                {% endif %}
                {% for date, events in groupedEvents %}
                    <h3 class="text-xl  ml-2 mb-2 badge py-4">{{ date }}:</h3>
                    <table class="w-full table table-compact">
                        <thead>
                        <tr>
                            <th>id</th>
                            <th>created At</th>
                            <th>start</th>
                            <th>finish</th>
                            <th class="w-[150px]">data</th>
                            <th>user ids</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for event in events %}
                            <tr>
                                <th>{{ event.id }}</th>
                                <th>{{ event.createdAt.format('Y-m-d h:i') }}</th>
                                <th>{{ event.start.format('Y-m-d h:i') }}</th>
                                <th>{% if event.finish %}
                                        {{ event.finish.format('Y-m-d h:i') }}
                                    {% endif %}</th>
                                <th class="whitespace-nowrap">{{ event.data|raw }}</th>
                                <th>
                                    {% for member in event.members %}
                                        <span class="mr-2">{{ member.id }}</span>
                                    {% endfor %}
                                </th>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endfor %}

            </div>
        {% endif %}

    </div>
{% endblock %}